services:
  # Aplicação Spring Boot
  - type: web
    name: beautysalon-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: beautysalon-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: beautysalon-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: beautysalon-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: beautysalon-db
          property: password
      - key: DB_URL
        value: "jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}"
      - key: RABBITMQ_ENABLED
        value: "false"

# Banco de Dados PostgreSQL Gratuito
databases:
  - name: beautysalon-db
    databaseName: beautysalon
    user: beautysalon_user
    plan: free
